CC = cc
CXX = cc
CFLAGS = -O

MAIN = gaussj
#OBJS = gaussj.o nrutil.o main.o
OBJS = gaussj.o nrutil.o gauss_driver.o
INC = nrutil.h nr.h
LIBS = 

all: $(MAIN)
$(OBJS): $(INC)

$(MAIN): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) $(LIBS) -lm  -o $@

clean:
	rm $(OBJS)
#############
SUFFIXES: .cc .cpp .c .o

.c.o:
	$(CC) $(CFLAGS) -c $<

.cpp.o:
	$(CXX) $(CFLAGS) -c $<

.cc.o:
	$(CXX) $(CFLAGS) -c $<
